### ISSUE TITLE
Emojis too large in Quill Editor

### ISSUE THREAD

**Issue by djamn** [xingw-z/quill2-emoji#1]
I use the following versions:
    "ngx-quill": "^25.3.2",
    "quill": "^2.0.2",
    "quill2-emoji": "^0.1.2",

I use Angular 17 (standalone)

        <quill-editor
          class="quill-editor-style"
          id="entry-text"
          formControlName="entry_message"
          [theme]="'snow'"
          [placeholder]="'"
          [modules]="quillModules"
          [formats]="['header', 'bold', 'italic', 'underline', 'strike', 'blockquote', 'list', 'indent', 'link', 'image', 'align', 'emoji', 'script', 'code-block', 'color', 'background', 'font']">
        </quill-editor>

When i insert emojis in my quill editor, the emojis are too large
![image](https://github.com/user-attachments/assets/86b328a6-2543-40bc-a8e0-2109e91083af)

**Comment by xingw-z** [comment]
> I use the following versions: "ngx-quill": "^25.3.2", "quill": "^2.0.2", "quill2-emoji": "^0.1.2",
> 
> I use Angular 17 (standalone)
> 
> ```
>     <quill-editor
>       class="quill-editor-style"
>       id="entry-text"
>       formControlName="entry_message"
>       [theme]="'snow'"
>       [placeholder]="'"
>       [modules]="quillModules"
>       [formats]="['header', 'bold', 'italic', 'underline', 'strike', 'blockquote', 'list', 'indent', 'link', 'image', 'align', 'emoji', 'script', 'code-block', 'color', 'background', 'font']">
>     </quill-editor>
> ```
> 
> When i insert emojis in my quill editor, the emojis are too large ![image](https://private-user-images.githubusercontent.com/87384392/358868595-86b328a6-2543-40bc-a8e0-2109e91083af.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQwNDAzNzAsIm5iZiI6MTcyNDA0MDA3MCwicGF0aCI6Ii84NzM4NDM5Mi8zNTg4Njg1OTUtODZiMzI4YTYtMjU0My00MGJjLWE4ZTAtMjEwOWU5MTA4M2FmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE5VDA0MDExMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRlNDRiOTBlY2RmNGFlYzNhOTcwNTE3YmY3YWNjNTcwMDFiYjE5N2Y4YzAxOGEwZTI1Njc5MjgzNjhjMDU5M2QmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.oR427xjvxYXz9rflVabaGn8WixVvThazDT3C775B_8c)

Is your OS Windows?

**Comment by djamn** [comment]
@xingw-z yess, I have Windows 10 and use Chrome Browser, sorry for the late response!

**Comment by djamn** [comment]
I fixed it changing the line-height and font-size of spans

`
.ql-editor span,
.text-base span {
  font-size: 1em;
  line-height: 1.2;
}
`

**Comment by xingw-z** [comment]
![image](https://github.com/user-attachments/assets/0787f694-787e-4a23-a85c-2ef6e6150e9e)
OK, but I wasn't able to replicate this issue on Windows 10.

**Comment by xingw-z** [comment]
Good,  nice try
